services:
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Kafka is available on port KAFKA_PORT inside the Docker network and on port KAFKA_SSL_PORT on localhost
      KAFKA_ADVERTISED_LISTENERS: "CLIENT://kafka:${KAFKA_PORT},EXTERNAL://localhost:${KAFKA_SSL_PORT}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
      - "${KAFKA_SSL_PORT}:${KAFKA_SSL_PORT}"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181