version: "3.9"

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.6.2
    container_name: kafka-kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka